################################
# Site Settings
################################
lang        : "en"
logo        :
title       : "Jekyll Test Site"
description : "A Jekyll test website with lots of posts"
author      : "Desired Persona"
email       : "hello@example..com"
newsletter  : "http://example.com/about"
baseurl     : "" # the subpath of your site, e.g. /blog
url         : "https://example.com"
date_format : "%-d %B %Y"
port        : 4000


################################
# Theme Settings
################################
remote_theme: desiredpersona/minimal-jekyll-theme
permalink   : /:title/

# Navigation Menus
header_navigation:
  - title: Home
    url: /
    
  - title: About
    url: /about/

  - title: Blog
    url: /blog/

  - title: Themes
    url: https://desiredpersona.com/themes/

footer_navigation:
  - title: Contact
    url: /contact/

  - title: privacy
    url: /privacy/

# UI Default Text
text:

  updated           : Updated          # Post updated text
  less_than         : Less than        # Post read time less than 1 minute
  minute_read       : min read         # Post read time
  words_per_minute  : 200              # Reading speed
  undefined_wpm     : Undefined parameter text.words_per_minute in your config.yml file
  caption           : Image            # Header image caption
  post_heading      : Latest Posts     # Latest posts heading
  post_limit        : 3                # Show this many latest post on the homepage
  blog_limit	      : 10               # Show this many post on the blog
  read_more         : Read more        # Read more link
  blog_title        : All Posts        # Archives link title
  blog_url          : /blog/           # Archive link url for home.html and 404 page layouts
  copyright         : 2015	           # The from year in the copyright. The current year is updated automatically.

# UI Default Settings
author_bio          : true             # Show author bio
post_meta           : true             # Show post meta
share_icons         : true             # Show post social sharing icons
category_tag_list   : true             # Show post categories & tags
twitter_icon        : true             # Show Twitter share button
facebook_icon       : true             # Show Facebook share button
google_plus_icon    : true             # Show Google+ share button

# Markdown Settings
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# Debug Liquid
#liquid:
#  error_mode:       warn
#  strict_filters:   true
#  strict_variables: true

#Sass
sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Include/Exclude filetypes
include:
  - _pages

exclude:
  - Gemfile.lock
  - node_modules

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: desired-persona-dev

# Theme Attribution Link (Optional)
# Setting this to false will remove the attribution link from the themes footer.
attribution: true 


################################
# Analytics Settings
################################
google_tag_manager: GTM-XXXXXXX


################################
# Jekyll Plugins
################################
plugins:
  - jekyll-archives
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap


# Jekyll SEO Tag Settings https://github.com/jekyll/jekyll-seo-tag
disable_title_output: true # Removes "| site title" from page <title> tag.

social:
  name: desired persona
  links:
    - https://twitter.com/desiredpersona
    - https://plus.google.com/+DesiredPersona

twitter:
  username: desiredpersona

webmaster_verifications:
  google: XX1234567891011121314
  bing: XX1234567891011121314
  alexa:
  yandex:


# Jekyll Feed Settings https://github.com/jekyll/jekyll-feed
atom_feed:
    path: # Leave blank to use default (feed.xml)


# Jekyll Archives Settings https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - month
    - day
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'